name: Release
on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: '1.23.1'
      - name: Build
        run: |
          make build -j6
          make package -j6
      - name: Create release
        uses: ncipollo/release-action@v1
        with:
          artifacts: 'dist/*.zip, dist/*.tar.gz'
          draft: true
